{"errorMessage": "An error occurred (AccessDeniedException) when calling the BatchWriteItem operation: User: arn:aws:sts::020856581528:assumed-role/mining-stock-app-LambdaExecutionRole-5hvo4qAHhtB6/SymbolIngest-dev is not authorized to perform: dynamodb:BatchWriteItem on resource: arn:aws:dynamodb:eu-west-2:020856581528:table/MiningSymbols-dev because no identity-based policy allows the dynamodb:BatchWriteItem action", "errorType": "ClientError", "requestId": "ab667c7d-2ad5-432c-a6f3-9e9c0beeef49", "stackTrace": ["  File \"/var/task/app.py\", line 78, in lambda_handler\n    batch.put_item(Item=symbol)\n", "  File \"/var/task/boto3/dynamodb/table.py\", line 167, in __exit__\n    self._flush()\n", "  File \"/var/task/boto3/dynamodb/table.py\", line 144, in _flush\n    response = self._client.batch_write_item(\n", "  File \"/var/task/botocore/client.py\", line 595, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n", "  File \"/var/task/botocore/context.py\", line 123, in wrapper\n    return func(*args, **kwargs)\n", "  File \"/var/task/botocore/client.py\", line 1058, in _make_api_call\n    raise error_class(parsed_response, operation_name)\n"]}